name: GJ Bail Bonds Inc.
favicon: null
layout_spectrum: 0.25121
typography_spectrum: 0.81418
title: GJ Bail Bonds Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7520415717735887
  lightness: 0.9242849673610181
  saturation: 0.4068954004906118
  rhythmicContrast: 0.37455881549976766
purpose: []
