name: Bail Bonds
favicon: null
layout_spectrum: 0.00775
typography_spectrum: 0.57767
title: Mr. Ocampo Bail Bonds
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.4068954004906118
  rhythmicContrast: 0.5
purpose: []
